[package]
name = "svp-client"
description = "The client side of the svp protocol, and a mock client for testing the server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
svp-common = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
